name: get_x_navigation_generator
description: Generate your getX navigator by annotating your screen 
version: 0.0.9
homepage: https://github.com/ikbendewilliam/get_x_navigation_generator

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^5.0.0
  build: ^2.3.1
  code_builder: ^4.4.0
  collection: ^1.16.0
  dart_style: ^2.2.4
  flutter:
    sdk: flutter
  glob: ^2.1.1
  path: ^1.8.2
  source_gen: ^1.2.6
  get_x_navigation_generator_annotations: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Comment before publishing
# dependency_overrides:
#   get_x_navigation_generator_annotations: 
#     path: ../get_x_navigation_generator_annotations

flutter:
