name: example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_x_navigation_generator_annotations: ^0.0.6
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  get_x_navigation_generator:
    path: ../

# Comment before publishing
dependency_overrides:
  get_x_navigation_generator_annotations: 
    path: ../../get_x_navigation_generator_annotations

flutter:
  uses-material-design: true
