name: get_x_navigation_generator_annotations
description: Generate your getX navigator by annotating your screen 
version: 0.1.0
homepage: https://github.com/ikbendewilliam/get_x_navigation_generator

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  get: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
