name: get_x_navigation_generator_annotations
description: Generate your getX navigator by annotating your screen 
version: 0.0.5
homepage: https://github.com/ikbendewilliam/get_x_navigation_generator

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  get: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
